[project]
name = "mcp-m365-filesearch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "beautifulsoup4>=4.13.3",
    "greenlet>=3.1.1",
    "html5lib>=1.1",
    "llama-index-core>=0.12.29",
    "mcp[cli]>=1.6.0",
    "msal>=1.32.0",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pillow>=11.1.0",
    "pymupdf>=1.25.5",
    "python-docx>=1.1.2",
    "python-pptx>=1.0.2",
    "torch>=2.6.0",
    "transformers>=4.51.1",
]
