services:
  - type: web
    name: mcp-sharepoint-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: CLIENT_ID
        sync: false
      - key: CLIENT_SECRET
        sync: false
      - key: TENANT_ID
        sync: false
      - key: AUTHORITY_URL
        value: https://login.microsoftonline.com
      - key: SCOPE
        value: https://graph.microsoft.com/.default
